### ISSUE TITLE
Sending custom types in synchronous channel fails with unhelpful error

### ISSUE THREAD

**Issue by Phasip** [utwente-fmt/spins#6]
File producing error: https://gist.github.com/Phasip/74780b9efb8b2bccdcdf

Gives error:

```
SpinS Promela Compiler - version 1.1 (3-Feb-2015)
(C) University of Twente, Formal Methods and Tools group

Parsing test.pml...
Parsing test.pml done (0.0 sec)

Optimizing graphs...
   RemoveUselessActions changed 0 states/transitions.
   RemoveUselessGotos changed 0 states/transitions.
   RenumberAll changed 7 states/transitions.
Optimization done (0.0 sec)

Generating next-state function ...
   Instantiating processes
Provide instantiation number for proctype Sender: 1
Provide instantiation number for proctype Receiver: 1
      #define __instances_Sender 1
      #define __instances_Receiver 1
   Creating state vector
   Statically binding references
      Statically binding chans of procinstance Sender_0 to run expression at l.18
      Statically binding chans of procinstance Receiver_0 to run expression at l.19
   Creating transitions
   Creating state labels
Generating next-state function done (1.0 sec)

Generating transitions/state dependency matrices (6 / 8 slots) ... 
   Found         19 /        104 ( 18.3%) Guard/slot reads               
   Found         15 /         48 ( 31.3%) Transition/slot tests               
java.lang.AssertionError: Inconclusive identifier for: sj_struct_Data_t
    at spins.promela.compiler.ltsmin.state.LTSminSubVectorStruct.mark(LTSminSubVectorStruct.java:46)
    at spins.promela.compiler.ltsmin.state.LTSminSubVectorArray.mark(LTSminSubVectorArray.java:80)
    at spins.promela.compiler.ltsmin.state.LTSminSubVectorStruct.mark(LTSminSubVectorStruct.java:56)
    at spins.promela.compiler.ltsmin.LTSminDMWalker$IdMarker.mark(LTSminDMWalker.java:446)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkExpression(LTSminDMWalker.java:507)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkAction(LTSminDMWalker.java:309)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkTransitions(LTSminDMWalker.java:221)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkModel(LTSminDMWalker.java:139)
    at spins.promela.compiler.ltsmin.LTSminTreeWalker.createLTSminModel(LTSminTreeWalker.java:192)
    at spins.Compile.writeLTSMinFiles(Compile.java:383)
    at spins.Compile.main(Compile.java:285)
Exception in thread "main" java.lang.AssertionError: Marking expression x failed with: java.lang.AssertionError: Inconclusive identifier for: sj_struct_Data_t
    at spins.promela.compiler.ltsmin.LTSminDMWalker$IdMarker.mark(LTSminDMWalker.java:449)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkExpression(LTSminDMWalker.java:507)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkAction(LTSminDMWalker.java:309)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkTransitions(LTSminDMWalker.java:221)
    at spins.promela.compiler.ltsmin.LTSminDMWalker.walkModel(LTSminDMWalker.java:139)
    at spins.promela.compiler.ltsmin.LTSminTreeWalker.createLTSminModel(LTSminTreeWalker.java:192)
    at spins.Compile.writeLTSMinFiles(Compile.java:383)
    at spins.Compile.main(Compile.java:285)
```

Increasing the channel size gives a better error ( java.lang.AssertionError: CustomVarTypes not supported in channel buffer ) - I am assuming CustomVarTypes are not supported in a synchronous channel either.

**Comment by alaarman** [comment]
At the moment, structs in channels and channels in channels are not supported ([1] should mention that). This should be reported as the error, so we will look into the crash and error report.

[1] van der Berg, Laarman (2012) SpinS: Extending LTSmin with Promela through SpinJa

**Comment by alaarman** [comment]
You can submit the contents of the struct separately over the channel though.

**Comment by alaarman** [comment]
Structs in channels are now supported (see master branch).
